version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    reviewers:
      - "judithspd"
      - "alvarolopez"
    assignees:
      - "judithspd"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "judithspd"
      - "alvarolopez"
